### ISSUE TITLE
[Feature Request]Introducing autoware runtime monitor for autoware fail safe action framework.

### ISSUE THREAD

**Issue by ZhenshengLee** [Autoware-AI/visualization#5]
### Description

autoware_health_checker, Emergency Handler and many other tools are packages of autoware fail safe action framework.

see [issue in gitlab](https://gitlab.com/autowarefoundation/autoware.ai/common/-/issues/4) https://github.com/Autoware-AI/autoware.ai/issues/1860 https://github.com/Autoware-AI/autoware.ai/issues/1986 for details.

This issue introduces [autoware_runtime_monitor](https://github.com/ZhenshengLee/autoware_runtime_monitor), which is inspired by [rqt_runtime_monotor](https://github.com/ros-visualization/rqt_runtime_monitor)

I'd like to merge this repo into autoware if possible.

Thanks.

**Comment by JWhitleyWork** [comment]
@ZhenshengLee While we really appreciate the request, Autoware.ai has gone into "maintenance only" which means we will no longer add or accept pull requests for new features in Autoware.ai going forward. Please consider contributing this functionality to Autoware.Auto which is being discussed here: https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/1233.
